import type { AppItem } from "./types";

export const PORTFOLIO_APPS: AppItem[] = [
  {
    id: "kalla-dms",
    title: "Kalla DMS // Real-Time Queue Display",
    icon: "📊",
    category: "ENTERPRISE QUEUE SYSTEM",
    tag: "LIVE SIMULATION",
    tagColor: "bg-[#006E5E] text-white border border-[#F2FEDC]/30",
    stack: ["React 19", "WebSockets", "Redis Streams", "Python FastAPI", "Docker"],
    shortDesc: "Sistem antrean loket multi-teller real-time dengan latensi sub-100ms dan audio voice synthesizer.",
    problem: "Antrean cabang konvensional sering mengalami desinkronisasi nomor panggil teller saat jaringan fluktuatif, menyebabkan kebingungan pengunjung dan kehilangan histori audit tiket.",
    solution: "Membangun arsitektur event-driven menggunakan Redis Pub/Sub dan WebSocket gateway. Menyediakan auto-reconnect fallback dan audio synthesizer lokal tanpa dependensi koneksi internet eksternal.",
    metrics: [
      { label: "LATENSI EVENT", value: "18ms" },
      { label: "UPTIME SLA", value: "99.98%" },
      { label: "DAILY TICKETS", value: "12,500+" },
      { label: "CONCURRENT USERS", value: "850+" },
    ],
    architecture: [
      { step: "01. Kiosk Ticket Dispenser", desc: "Thermal printer memicu event POST pembuatan tiket unik." },
      { step: "02. Redis Stream Ingress", desc: "Event di-serialize dan diantrekan ke kanal teller terisolasi." },
      { step: "03. WebSocket Broadcast", desc: "Server mem-push pembaruan tiket ke seluruh monitor display dalam 18ms." },
      { step: "04. Voice Chime Synthesizer", desc: "Display TV memanggil nomor antrean secara otomatis via Web Audio API." },
    ],
    demoUrl: "https://github.com/rezkimd",
    repoUrl: "https://github.com/rezkimd",
  },
  {
    id: "erp-odoo",
    title: "Odoo 16/18 ERP Procurement & Inventory",
    icon: "📦",
    category: "ENTERPRISE SOLUTIONS",
    tag: "ERP ARCHITECTURE",
    tagColor: "bg-[#CBB800] text-[#241D00] border border-[#3A2F00]",
    stack: ["Python", "Odoo 18", "PostgreSQL", "Docker Swarm", "REST API"],
    shortDesc: "Modul rantai pasok custom untuk otomasi approval berjenjang, batch barcode scanning, dan rekonsiliasi buku besar.",
    problem: "Proses procurement manual rentan duplikasi pesanan pembelian (PO) serta selisih stok fisik vs catatan sistem hingga miliaran rupiah.",
    solution: "Mengintegrasikan engine approval matrix berbasis role hierarkis, barcode scanning serial number, dan webhooks ke sistem perbankan korporasi.",
    metrics: [
      { label: "REKONSILIASI STOK", value: "99.99%" },
      { label: "WAKTU APPROVAL", value: "-75%" },
      { label: "TRANSAKSI BULANAN", value: "45,000+" },
      { label: "SQL QUERY TUNING", value: "42% Faster" },
    ],
    architecture: [
      { step: "01. Purchase Requisition", desc: "Unit bisnis mengajukan anggaran belanja dengan kuota terikat." },
      { step: "02. Dynamic Matrix Approval", desc: "Notifikasi otomatis ke level Manajer hingga Direksi via push webhook." },
      { step: "03. Barcode Warehouse Inbound", desc: "Penerimaan barang dengan verifikasi serial QR instan di mobile scanner." },
      { step: "04. Auto General Ledger", desc: "Jurnal akuntansi terbentuk otomatis saat good receipt divalidasi." },
    ],
    demoUrl: "https://github.com/rezkimd",
    repoUrl: "https://github.com/rezkimd",
  },
  {
    id: "re-port",
    title: "re-port // Spatial Desk Workspace",
    icon: "🖥️",
    category: "CREATIVE ENGINEERING",
    tag: "PURE SVG VECTORS",
    tagColor: "bg-[#29A18D] text-white",
    stack: ["React 19", "Turborepo", "TypeScript Strict", "Tailwind v4", "TanStack"],
    shortDesc: "Ruang kerja virtual interaktif dengan kamera sudut pandang spasial, manipulasi SVG murni, dan animasi origami kertas.",
    problem: "Sebagian besar portofolio developer berbentuk landing page kartu datar yang generik dan membosankan tanpa karakter visual.",
    solution: "Mendesain kanvas ruangan meja kerja taktil skeuomorfik 1920x1080 murni berbasis vektor SVG tanpa gambar bitmap placeholder, dilengkapi transisi state yang hidup.",
    metrics: [
      { label: "BITMAP SLOP", value: "0 Images" },
      { label: "SVG FIDELITY", value: "100% Vector" },
      { label: "LIGHTHOUSE SCORE", value: "100/100" },
      { label: "RESPONSIVE RATIO", value: "16:9 Adaptive" },
    ],
    architecture: [
      { step: "01. Penpot Vector Mastery", desc: "Pemodelan 19 board skenario spasial dengan token warna terkontrol." },
      { step: "02. React 19 Vector Canvas", desc: "Hierarki layer arsitektur ruangan, pencahayaan, dan hotspot interaktif." },
      { step: "03. CSS Origami Keyframes", desc: "Animasi pelipatan surat tri-fold dan pergerakan binder ordner 3D." },
      { step: "04. Strict Contract State", desc: "Zod validation, typecheck zero error, dan arsitektur monorepo modular." },
    ],
    demoUrl: "https://github.com/rezkimd/re-port",
    repoUrl: "https://github.com/rezkimd/re-port",
  },
  {
    id: "iot-telemetry",
    title: "Industrial IoT Machinery Telemetry",
    icon: "⚙️",
    category: "HARDWARE & IOT",
    tag: "TELEMETRY STREAM",
    tagColor: "bg-[#E07A5F] text-white",
    stack: ["MQTT Broker", "Node.js", "InfluxDB", "Grafana", "ESP32 C++"],
    shortDesc: "Pemantauan getaran, suhu motor, dan konsumsi daya mesin manufaktur frekuensi tinggi dengan peringatan anomali.",
    problem: "Kerusakan mesin mendadak menimbulkan *downtime* pabrik yang memakan biaya besar karena ketiadaan sistem pemeliharaan prediktif.",
    solution: "Pemasangan sensor getaran 3-axis berbasis microcontroller ESP32 yang menyalurkan telemetri via MQTT ke time-series database InfluxDB dengan deteksi anomali ambang batas.",
    metrics: [
      { label: "SAMPLING RATE", value: "100 Hz" },
      { label: "ALERT NOTIFICATION", value: "<1.2s" },
      { label: "DOWNTIME PREVENTION", value: "35% Reduced" },
      { label: "SENSOR NODES", value: "48 Active" },
    ],
    architecture: [
      { step: "01. Microcontroller Sensing", desc: "ESP32 membaca akselerometer & sensor arus via I2C/SPI bus." },
      { step: "02. MQTT Payload Packet", desc: "Data dikompresi dan dikirim ke broker EMQX dengan TLS encryption." },
      { step: "03. InfluxDB Time-Series", desc: "Penyimpanan metrik ribuan titik per detik dengan retensi data 1 tahun." },
      { step: "04. Anomaly Threshold Hook", desc: "Jika getaran melebihi standar ISO 10816, sirine dan webhook WhatsApp aktif." },
    ],
    demoUrl: "https://github.com/rezkimd",
    repoUrl: "https://github.com/rezkimd",
  },
  {
    id: "auth-gateway",
    title: "Microservice Auth & Rate Limiter Gateway",
    icon: "🔒",
    category: "BACKEND INFRASTRUCTURE",
    tag: "SUB-5MS LATENCY",
    tagColor: "bg-[#877B00] text-white",
    stack: ["Go (Golang)", "Redis", "JWT Ed25519", "Docker", "Prometheus"],
    shortDesc: "Reverse proxy otentikasi performa ultra tinggi dengan token bucket dynamic rate limiting dan circuit breaker.",
    problem: "Layanan microservices sering terhambat oleh overhead validasi token otentikasi sentral yang lambat dan rentan serangan DDoS.",
    solution: "Gateway berbasis Golang dengan algoritma kurva elips Ed25519 dan cache in-memory Redis cluster yang memproses validasi token dalam kurang dari 3ms.",
    metrics: [
      { label: "AUTH LATENCY", value: "2.8ms" },
      { label: "THROUGHPUT", value: "45k req/s" },
      { label: "CPU FOOTPRINT", value: "<120MB RAM" },
      { label: "CIRCUIT TRIP TIME", value: "50ms" },
    ],
    architecture: [
      { step: "01. Client Request Ingress", desc: "Request diterima oleh high-performance Go reverse proxy handler." },
      { step: "02. Token Cache Lookup", desc: "Verifikasi signature Ed25519 dan pengecekan blacklist token di Redis." },
      { step: "03. Token Bucket Limiter", desc: "Memastikan IP/User tidak melebihi kuota 500 req/min secara presisi." },
      { step: "04. Downstream Forward", desc: "Header user yang terdekripsi diteruskan ke backend service internal." },
    ],
    demoUrl: "https://github.com/rezkimd",
    repoUrl: "https://github.com/rezkimd",
  },
  {
    id: "cicd-swarm",
    title: "Automated DevOps CI/CD Swarm",
    icon: "🚀",
    category: "CLOUD INFRASTRUCTURE",
    tag: "ZERO-DOWNTIME",
    tagColor: "bg-white text-[#241D00] border border-[#3A2F00]",
    stack: ["GitHub Actions", "Docker Swarm", "Traefik", "Prometheus", "Bash"],
    shortDesc: "Pipeline pengiriman kontainer otomatis dengan strategi rolling update, canary testing, dan auto rollback.",
    problem: "Deploy aplikasi sering menyebabkan interupsi layanan (*service blackout*) bagi pengguna aktif saat versi baru dirilis.",
    solution: "Mengatur orkestrasi Docker Swarm cluster dengan reverse proxy Traefik yang mengarahkan trafik hanya ke kontainer yang telah lulus *healthcheck*.",
    metrics: [
      { label: "DEPLOYMENT DOWNTIME", value: "0 Seconds" },
      { label: "ROLLBACK TIME", value: "<8s" },
      { label: "BUILD SPEED", value: "3.2m Avg" },
      { label: "CLUSTER NODES", value: "5 Nodes" },
    ],
    architecture: [
      { step: "01. Git Tag Trigger", desc: "Commit tag vX.Y.Z memicu pipeline GitHub Actions dengan build multi-arch." },
      { step: "02. Image Scanning & Push", desc: "Vulnerability scanner memindai image sebelum di-push ke private registry." },
      { step: "03. Rolling Swarm Deploy", desc: "Kontainer diperbarui bergantian 1 demi 1 tanpa memutus koneksi aktif." },
      { step: "04. Health Probe & Certs", desc: "Traefik memvalidasi HTTP 200 dan memperbarui sertifikat SSL Let's Encrypt." },
    ],
    demoUrl: "https://github.com/rezkimd",
    repoUrl: "https://github.com/rezkimd",
  },
];
